version: '2'
services:

  dbmysql:
    image: mysql:5.5
    volumes:
        # this is to execute the create db on start
        - ./ddl:/docker-entrypoint-initdb.d
    #   eventually mount db folders on the host
    #    - ./data/mysql:/var/lib/mysql
    #    - ./docker/mysql.d:/etc/mysql/conf.d
    ports:
        - 3306
    environment:
        MYSQL_DATABASE: openspcoop2
        MYSQL_USER: openspcoop2
        MYSQL_ROOT_PASSWORD: openspcoop2

  openspcoop2:
    build: .
    #environment:
    #    VIRTUAL_HOST: data.portaportese.it
    #    VIRTUAL_PORT: 8080
    ports:
        - 8080
    depends_on:
        - dbmysql
