version: '2'
services:

  openspcoop2:
    container_name: service
    build: .
    ports:
        - 8080
    depends_on:
        - mydatabase
    #command: ["/bin/bash", "-c", "sleep 30s"]

  mydatabase:
    container_name: database
    image: postgres:9.4
    volumes:
        # this is to execute the DDL on start
        - ./dist/sql:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_DB: openspcoop2
        POSTGRES_USER: openspcoop2
        POSTGRES_PASSWORD: openspcoop2
