version: '2'
services:

  openspcoop2:
    container_name: service
    build: openspcoop2img
    ports:
        - 8080:8080
        - 9990:9990
    depends_on:
        - mydatabase

  mydatabase:
    container_name: database
    image: postgres:9.4
    volumes:
        # this is to execute the DDL on start
        - ./openspcoop2img/dist/sql:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_DB: openspcoop2
        POSTGRES_USER: openspcoop2
        POSTGRES_PASSWORD: openspcoop2
